# ---- Dev stage ----
FROM node:22-alpine AS dev

WORKDIR /app

EXPOSE 5173

# Remove package-lock e node_modules gerados no host (Windows/Mac)
# e reinstala tudo com binarios Linux corretos
CMD sh -c "rm -rf node_modules package-lock.json && npm install && npm run dev -- --host"


# ---- Build stage ----
FROM node:22-alpine AS build

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build


# ---- Prod stage (serve com nginx) ----
FROM nginx:alpine AS prod

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]